### ISSUE TITLE
add validator for input

### ISSUE THREAD

**Issue by alisharify7** [mzarchi/telethon-scripts#1]
hi can i create a pr for adding some validator for input in app
like validator for getting user's phone number ?

**Comment by mzarchi** [comment]
We need this, thanks for the contribution

**Comment by alisharify7** [comment]
> We need this, thanks for the contribution

Another issue is present in codes/login.py . in the first few lines, you're importing config file but the import is totally wrong, because config file is in parent directory, and it's not gonna working, can i fixed that too ?

**Comment by mzarchi** [comment]
> > We need this, thanks for the contribution
> 
> Another issue is present in codes/login.py . in the first few lines, you're importing config file but the import is totally wrong, because config file is in parent directory, and it's not gonna working, can i fixed that too ?

Of course, but this depends on the type of extension in the directory, anyway thanks for solving this problem
